### PR TITLE
Refine yt version selection

### PR DESCRIPTION
**Pull request by astrofrog**
The bug was specifically in 3.3.0 and 3.3.1 but works with >= 3.3.2

### CODE REVIEW

**Comment by jakirkham** [comment]
This needs a [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` version `1.7.0`.

**Comment by jakirkham** [comment]
Is it just that we need `sphinx`? We can re-render that for Python 3.6.

**Comment by astrofrog** [comment]
@jakirkham - no, this was because we bundle numpydoc and this version had small Python 3.6 incompatibilities. The only solution for this release is to remove the sub-packages (which aren't really public API, just used when building the docs) and the next release of Hyperion will support 3.6 properly (I'm removing the bundled numpydoc).

**Comment by astrofrog** [comment]
@jakirkham - however, this is going to fail because yt for Python 3.6 didn't get uploaded for Linux: https://github.com/conda-forge/yt-feedstock/issues/16 - any ideas on that issue?

**Comment by astrofrog** [comment]
Strangely the build for CircleCi here ends with:

```
TEST START: hyperion-0.9.8-np110py36_2
Deleting work directory, /feedstock_root/build_artefacts/recipe_root_1483868078529/work/Hyperion-0.9.8
...WARNING conda_build.build:create_env(711): failed to create env, retrying.  exception was: The following specifications were found to be in conflict:
  - hyperion 0.9.8 np110py36_2
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
...WARNING conda_build.build:create_env(711): failed to create env, retrying.  exception was: The following specifications were found to be in conflict:
  - hyperion 0.9.8 np110py36_2
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
...WARNING conda_build.build:create_env(711): failed to create env, retrying.  exception was: The following specifications were found to be in conflict:
  - hyperion 0.9.8 np110py36_2
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
...ERROR conda_build.build:create_env(715): Failed to create env, max retries exceeded.
Can't build /recipe_root due to unsatisfiable dependencies:
The following specifications were found to be in conflict:
  - hyperion 0.9.8 np110py36_2
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

without further explanation. But I'm pretty sure it's because yt (runtime dependency) isn't available for Python 3.6 on Linux.

**Comment by jakirkham** [comment]
You're probably right in assuming `yt`. ATM `conda` is not great about explaining unsatisfied dependencies, but looking for dependencies missing Python 3.6 packages is a good first step.

Commented on the aforementioned issue. We can keep that discussion there.

Other things you can try is skipping Python 3.6 in the interim while things get sorted. Just add `skip: true [py==36]` to do this. May need to combine using `or` with other selectors (e.g. Windows).

**Pull request merged**
